# Generated by Django 4.2.14 on 2024-08-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=100, verbose_name='商品条码')),
                ('parent_barcode', models.CharField(max_length=100, verbose_name='父条码')),
                ('group_sn', models.CharField(max_length=100, verbose_name='国际码')),
                ('name', models.CharField(max_length=100, verbose_name='商品名称')),
                ('col', models.CharField(max_length=50, verbose_name='颜色')),
                ('size', models.CharField(max_length=50, verbose_name='尺寸')),
                ('dept_name', models.CharField(max_length=50, verbose_name='大类')),
                ('big_category_name', models.CharField(max_length=50, verbose_name='中类')),
                ('small_category_name', models.CharField(max_length=50, verbose_name='小类')),
                ('season', models.CharField(max_length=50, verbose_name='季节')),
                ('gender', models.CharField(max_length=50, verbose_name='性别')),
                ('market_price', models.FloatField(verbose_name='市场价')),
                ('brand_alias', models.CharField(max_length=50, verbose_name='品牌别名')),
            ],
        ),
    ]
